[colors.primary]
background = "#011627"
foreground = "#D6DEEB"

[colors.cursor]
cursor = "#D6DEEB"
text = "#011627"

[colors.normal]
black = "#011627"
red = "#EF5350"
green = "#22DA6E"
yellow = "#ADDB67"
blue = "#82AAFF"
magenta = "#C792EA"
cyan = "#21C7A8"
white = "#FFFFFF"

[colors.bright]
black = "#575656"
red = "#EF5350"
green = "#22DA6E"
yellow = "#FFEB95"
blue = "#82AAFF"
magenta = "#C792EA"
cyan = "#7FDBCA"
white = "#FFFFFF"
